export { HomePage } from './HomePage'
export { default as LoginPage } from './LoginPage'
export { default as SignupPage } from './SignupPage'
export { default as AuthCallbackPage } from './AuthCallbackPage'
export { default as FavouritePage } from './FavouritePage'
export { default as ViewHistoryPage } from './ViewHistoryPage'
export { default as PropertyDetailPage } from './PropertyDetailPage'